astrocamp/18th-Trico

core/settings.py, core/urls.py, frontend/styles/app.css, package-lock.json, package.json, pages/templates/pages/home.html, pages/urls.py, pages/views.py, postcss.config.js, tailwind.config.js, templates/shared/layout.html, templates/shared/navbar.html, users/admin.py, users/apps.py, users/forms.py, users/models.py, users/templates/users/login.html, users/templates/users/register.html, users/tests.py, users/urls.py, users/views.py
Resolve issue #14 
- 建立users app ，並建立登入的框架
- 使用username及password進行登入驗證
- 處理登入不成功時跳出的提示文字“登入失敗，請重新登入一次。”
- 使用username及password1、password2進行註冊
- 並使得註冊失敗時跳出“很抱歉，您註冊失敗!!”
- 註冊成功時會跳轉至登入畫面，並顯示“註冊成功!!!歡迎登入”
- 製作簡易navbar模板，整合到navbar.html
- 讓登入登出畫面顯示不同
- 建立一個空的pages首頁頁面
=> [add] 新增使用者登入、註冊功能、做navbar

pages/templates/pages/client.html, pages/templates/pages/freelancer.html, pages/urls.py, pages/views.py
=> [add] 建立接案者與業者資料頁面

templates/shared/navbar.html, users/templates/users/switch_client.html, users/templates/users/switch_freelancer.html, users/urls.py, users/views.py
=> [add] 新增點擊頭像按鈕，可轉換頁面至業者及接案者的頁面

README.md, categories/management/commands/seed_categories.py, pages/templates/pages/home.html, pages/views.py, users/templates/users/freelancer_dashboard.html
本次 PR 包含以下修改內容： 
1. 在首頁新增分類的頁籤功能，提升用戶瀏覽分類的便捷性。  
2. 在會員管理頁新增服務管理的超連結，便於用戶快速進入服務管理功能。  
3. 修正 Django Seed 重複匯入相同分類名稱的問題，避免資料異常。
1. **首頁**  
- 新增分類頁籤，提供簡潔的分類瀏覽功能。
2. **會員管理**  
- 新增服務管理的超連結，優化用戶操作體驗。
3. **Django Seed**  
- 修正分類名稱的重複匯入問題，確保資料唯一性。
- 測試新增功能在多瀏覽器環境下的顯示與運行效果。  
- 優化分類頁籤的樣式與互動設計。
- 驗證首頁分類頁籤是否正確顯示並正常切換分類。  
- 測試會員管理中的服務管理連結是否正常運作。  
- 確認 Django Seed 的分類匯入邏輯已修正，無重複資料。
=> [feat] 新增分類頁籤與服務管理連結，修正分類匯入問題

comments/models.py, comments/templates/comments/add_comment.html, comments/templates/comments/delete_comment.html, comments/views.py, frontend/scripts/app.js, services/templates/services/freelancer_dashboard.html, static/styles/tailwind.css, users/templates/users/feedback.html, users/templates/users/login.html, users/views.py
=> [fix] 刪除不必要註解及CDN

.gitignore, frontend/scripts/App.vue, frontend/scripts/app.js, package-lock.json, package.json, staticfiles/scripts/app.js, staticfiles/styles/app.css, staticfiles/styles/tailwind.css, tailwind.config.js
本次 PR 的主要內容如下：
1. **移除 Vue 中不必要的代碼**：
- 清理了 Vue 組件中未被使用的多餘代碼。
- 優化代碼結構，提升可讀性與維護性。
2. **排除影響 Vue 功能的原生 JS 檔案**：
- 將部分可能與 Vue 功能衝突的原生 JavaScript 文件從 `static` 資料夾中移除。
- 確保項目中 Vue 功能的穩定性與正確運作。
此提交旨在減少代碼冗餘、提升專案運行效率，並解決可能的功能衝突問題，請協助審核，謝謝！ 😊
=> [refactor] 移除多餘 Vue 代碼並排除影響功能的原生 JS 檔案

services/templates/services/search_results.html, services/views.py
=> [fix] 修正留言區塊

core/settings.py
1. **環境變數管理：**
- 將資料庫的 `DB_PORT`、`DB_HOST`、`DB_ENGINE` 從原本的 `settings.py` 中移除，並改為透過環境變數管理。
- 增加 `.env` 讀取邏輯，確保敏感資訊不會硬編碼於程式中。
---
- 測試不同環境變數組合下，資料庫連線是否正常。
- 測試 `.env` 文件未設置時，是否能使用預設值。
- 確保 `.env.example` 提供完整的參數範例，方便新成員配置。
---
- 提高程式碼安全性，避免敏感資訊洩漏。
- 提升部署靈活性，適應不同伺服器與環境的需求。
- 透過 `.env.example`，讓新加入的開發者更容易理解專案環境配置。
=> [chore] 將資料庫設定 (DB_PORT, DB_HOST, DB_ENGINE) 移動至環境變數

core/settings.py
1. **目錄路徑統一小寫：**
- 將 `DIRS` 配置中的路徑統一調整為小寫，提升路徑命名的一致性與可讀性。
- 此改動避免了大小寫敏感系統（如 Linux）中的潛在問題，確保跨平台的穩定性。
2. **`settings.py` 修改範例：**
```python
"DIRS": [BASE_DIR / "templates"],  # 確保小寫
```
---
- 確認調整後的路徑是否在大小寫敏感的系統（如 Linux）中正常運行。
- 測試模板載入是否正確，確認頁面渲染未受影響。
- 確保開發和生產環境的設定一致。
---
- 提升專案的代碼一致性，增強可維護性。
- 減少因大小寫路徑問題引起的潛在錯誤。
- 保證跨平台的兼容性與穩定性。
=> [chore] 調整模板目錄路徑為小寫以保持一致性

core/settings.py
1. **移除註解表情符號：**
- 清除了程式碼註解中的表情符號，以提升程式碼可讀性與專業度。
- 表情符號可能在不同編輯器與終端機中顯示不一致，移除後可確保跨平台的一致性。
---
- 已檢查所有註解內容，確保僅移除表情符號，未影響邏輯說明。
- 進行基本測試，程式碼執行無誤。
---
- 提升程式碼專業度與一致性。
- 使註解更具可讀性，符合清潔程式碼原則。
- 減少可能因表情符號導致的顯示相容性問題。
=> [chore] 移除註解中的表情符號

core/settings.py
---
- 在本地測試啟用 `DEBUG=True` 以確認錯誤訊息正常顯示。
- 在生產測試環境下設置 `DEBUG=False`，並確認錯誤訊息未直接暴露。
- 確保靜態檔案能正常加載且錯誤頁面處理得當。
---
- 提高生產環境的安全性，防止錯誤訊息洩露。
- 提升設定靈活性，透過環境變數控制不同環境的 `DEBUG` 狀態。
- 符合 Django 官方安全性最佳實踐。
=> [chore] 設定 DEBUG=False 以符合生產環境安全需求

core/settings.py
1. **啟用 `DEBUG` 模式：**
- 將 `settings.py` 中的 `DEBUG` 參數設為 `True`，方便在開發環境中進行除錯與錯誤追蹤。
- `DEBUG` 模式允許顯示完整的錯誤訊息，有助於識別與解決問題。
---
- 在開發環境下測試 `DEBUG=True` 是否正常顯示完整的錯誤訊息。
- 確保 `.env` 設定能正確控制 `DEBUG` 狀態。
---
- 方便開發人員在本地除錯，提升開發效率。
- 提供靈活的環境變數控制，便於快速切換不同環境的設定。
- 僅適用於開發環境，生產環境需將 `DEBUG` 設定為 `False` 以維護安全性。
=> [chore] 設定 DEBUG=True 以符合開發環境需求

core/settings.py
=> [fix] 修正google第三方登入

core/settings.py, notification/views.py, services/templates/services/service_detail.html, templates/shared/navbar.html
1.改善 Navbar 原本閃跳問題。
2.刪除多餘的鈴鐺通知數字。
3.確保下拉通知欄不被其他元件遮蓋。
=> [fix] 鈴鐺通知修正

core/settings.py, users/templates/users/feedback.html, users/views.py
調整評價與回饋區的間距，移除 emojis，統一顏色為藍色，將評論區與按愛心的服務區改為上下排列，並讓按愛心的服務同時顯示於接案者和業者的評價與回饋區頁面。此外，優化按過愛心的服務卡牌樣式，提升展示效果。
=> [fix] 調整評價與回饋區

contact/templates/contact/contact.html, contact/views.py, core/settings.py
若用戶當初透過 Google 第三方登入或手動註冊，系統在用戶聯繫客服時會自動填入其電子郵件，提升使用便利性。
=> [add] 聯繫客服區自動填入用戶的電子郵件

categories/templates/categories/tag.html, services/templates/services/service_detail.html, templates/shared/navbar.html
1. **標籤卡牌樣式調整：**
- 重新設計標籤卡牌樣式，使版型更加一致且美觀。
- 優化標籤間距與對齊方式，提升視覺一致性。
2. **服務內容介紹頁優化：**
- 重新調整服務內容介紹頁的排版，確保更符合現代化版型設計。
- 新增 RWD（響應式設計），讓頁面能在不同裝置上自適應顯示，提升使用者體驗。
3. **頁首搜尋框調整：**
- 針對行動裝置（手機版）優化搜尋框樣式。
- 在手機版下，隱藏「三合」品牌字，以保留更多版面空間，並提升搜尋功能的可見性與易用性。
---
- 測試了標籤卡牌樣式於桌面版與手機版的呈現效果。
- 驗證服務內容介紹頁的 RWD 是否能正常顯示於不同螢幕尺寸。
- 測試搜尋框在行動裝置上的隱藏效果，並確保桌面版顯示正常。
- 驗證不同解析度下的版面穩定性與美觀度。
---
- 提升整體 UI 一致性與視覺美觀度。
- 提高服務介紹頁在行動裝置上的可讀性與使用體驗。
- 優化搜尋框設計，使行動裝置下更加專注於搜尋功能。
- 符合響應式設計原則，提升跨裝置瀏覽體驗。
=> [style] 重新調整標籤卡牌、服務介紹頁與搜尋框 RWD 優化

categories/templates/categories/category.html, categories/templates/categories/tag.html, categories/views.py, pages/templates/pages/service_card.html, search/templates/search.html, search/views.py, services/templates/services/service_detail.html
=> [feat] 實現愛心按鈕在分類、標籤、搜尋頁面的同步點擊功能

services/templates/services/freelancer_dashboard.html
=> [fix] 移除個人服務管理中的留言功能，並微幅調整樣式

users/templates/users/client_dashboard.html, users/templates/users/freelancer_dashboard.html, users/views.py
Resolved #192 
- 優化輸入欄位行為：將 "None" 值統一顯示為空白，提升使用者體驗。
- 修復登出後仍顯示上一個登入成功訊息的問題。
=> [fix] 修正個人資料頁面、登入時的錯誤訊息

users/templates/users/client_dashboard.html, users/templates/users/feedback.html, users/templates/users/freelancer_dashboard.html, users/templates/users/likes.html, users/urls.py, users/views.py
###將留言區塊與愛心區塊獨立至不同頁面，並新增點擊功能，方便直接跳轉至服務頁面查看相關詳情。
=> [fix] 評價與回饋 ＆ 愛心收藏

order/views.py
Resoved #200 
- 當綠界支付完成並回傳結果時，原先的邏輯未正確處理狀態轉換，導致訂單狀態無法從 pending（0）正確轉為 paid（1）。導致用戶支付成功但訂單顯示未完成的情況。
- 新增綠界回傳值的解析邏輯，確保接收到資訊後更新訂單狀態。
- 透過狀態機執行狀態轉換（pending -> paid）。
- 增強錯誤處理機制，記錄回傳異常情況以便於後續調試。
=> [fix]: 修正綠界回傳值狀態

common/views.py, core/settings.py, frontend/scripts/components/NotFoundPage.vue, static/scripts/app.css
1. **404 頁面重新設計：**
- 為 404 錯誤頁面設計了全新版型，提升頁面整體美觀度與功能性。
- 新設計包含以下特點：
- 視覺化的錯誤提示，讓用戶更直觀理解當前狀況。
- 提供返回首頁或繼續瀏覽的快速操作按鈕，減少用戶困惑。
- 支援響應式設計，確保在不同裝置上顯示良好。
2. **前端優化：**
- 使用現代化樣式設計（如 Flexbox 或 CSS Grid）確保排版結構清晰。
- 適當加入動畫或插圖，為用戶提供更友善的錯誤處理體驗。
---
- 在多種情境下觸發 404 頁面，驗證其是否正確顯示。
- 測試返回首頁與其他操作按鈕的功能是否正常。
- 確保在不同螢幕尺寸與裝置上的顯示效果一致。
- 驗證頁面載入性能是否符合預期。
---
- 提升用戶在找不到頁面時的體驗，減少挫折感。
- 增強系統的友好度與品牌專業形象。
- 提供更便利的導引功能，提升用戶繼續瀏覽的可能性。
=> [style] 重新設計 404 錯誤頁面，提升用戶體驗
